services:
  - type: web
    name: og-chain-node-enhanced
    env: docker
    plan: pro # Using your existing Pro plan
    region: oregon
    dockerfilePath: ./Dockerfile.enhanced
    dockerContext: ./
    envVars:
      - key: OFFICIAL_RPC
        value: https://evmrpc.0g.ai/
      - key: TESTNET_RPC
        value: https://evmrpc-testnet.0g.ai/
      - key: PROXY_PORT
        value: 26657
      - key: MONITORING_PORT
        value: 9615
      - key: NODE_ENV
        value: production
      - key: PM2_INSTANCES
        value: 4
    # No disk needed - proxy doesn't store data!
    healthCheckPath: /health
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 4000m # Full Pro plan CPU for maximum performance
      memory: 16Gi # Full Pro plan memory for connection pooling

# ✅ SEAMLESS BENEFITS:
# - Instant startup (no sync required)
# - Uses official 0G infrastructure (100% reliable)
# - Enhanced monitoring and statistics
# - Load balancing with PM2 (4 processes)
# - Full RPC compatibility with your existing commands
# - Pro plan resources optimized for performance
# - Real-time access to latest blockchain state
